services:
  configurator:
    environment:
      REDIS_CACHE: redis-cache:6379
      REDIS_QUEUE: redis-queue:6379
    depends_on:
      - redis-cache
      - redis-queue

  redis-cache:
    image: redis:6.2-alpine
    volumes:
      - redis-cache-data:/data

  redis-queue:
    image: redis:6.2-alpine
    volumes:
      - redis-queue-data:/data

volumes:
  redis-cache-data:
    name: ${PROJECT_NAME}_redis-cache-data
    external: true
  redis-queue-data:
    name: ${PROJECT_NAME}_redis-queue-data
    external: true
  redis-socketio-data:
    name: ${PROJECT_NAME}_redis-socketio-data
    external: true
